### ISSUE TITLE
Change version and duration for stalebot

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/TakeTwo#29]
### Background on the problem the feature will solve/improved user experience
Stalebot defaults are not too short for the team. The version also needs to be updated.

### Tasks 
In the `.github/workflows/stale.yml` file:
- [ ] update version to `actions/stale@v4`
- [ ] change `days-before-stale: 60`
- [ ] change `days-before-close:90`

### Acceptance Criteria 
Stalebot `version`, `days-before-close`, and `days-before-stale` are updated

FYI @demilolu @naagma5
