### ISSUE TITLE
TakeTwo Documentation Updates

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/TakeTwo#30]
## Background

TakeTwo has existing documentation across its chrome extension, web api and machine learning components. We would like you try out the application and suggested improvements to the documentation. 

## Tasks

Fixing existing Documentation
- [ ] Check out the open documentation issues
- [ ] Read & follow the instructions in the Getting Started section of the readme.md to set the solution up in:
-  https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo
- https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension
- https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI
- https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-DataScience (if applicable)

If any directions are unclear, outdated:
- [ ] create a new issue using the documentation template
- [ ] label it  'documentation' 'ms-cohort-claimed' and assign the issue to yourself,
- [ ] Discuss your changes in the issue
