### ISSUE TITLE
Starter Kit: Unit Testing in  TakeTwo repositories

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/TakeTwo#34]
### Background on the problem the feature will solve/improved user experience
Our code currently lacks unit testing, which is needed for test driven development practices: easy debugging, functional testing, etc. 

### Describe the solution you'd like
Provide unit tests for various TakeTwo repositories:

- [ ] https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension
- [ ] https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-DataScience/
- [ ] https://github.com/Call-for-Code-for-Racial-Justice/taketwo-webapi/

### Tasks 
- [ ] research existing tests of similar code bases
- [ ] document list of tests to be implemented for each repository based on programming language, architecture, etc
- [ ] create Github issues for each test in the appropriate repo and link to this issue as well
- [ ] implement changes in each repository as appropriate

### Acceptance Criteria 

- [ ] At least 60% code coverage by unit tests
